[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "google-generativeai>=0.8.5",
    "pandas>=2.2.3",
    "pypdf2>=3.0.1",
    "python-pptx>=1.0.2",
    "streamlit>=1.44.1",
]
